CryptoChecker/Models/Currency.cs
namespace CryptoChecker.Models
{
    public class Currency
    {
        #region Variables

        public string Name { get; set; } = string.Empty;
        public decimal Price { get; set; }

        #endregion
    }
}

CryptoChecker/Models/ErrorViewModel.cs
namespace CryptoChecker.Models
{
    public class ErrorViewModel
    {
        #region Variables

        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        #endregion
    }
}

CryptoChecker/Models/QuotesModel.cs
namespace CryptoChecker.Models
{
    public class QuotesModel
    {
        #region Variables
        public string Name { get; set; } = string.Empty;
        public string Symbol { get; set; } = string.Empty;
        public IEnumerable<Currency>? Currency { get; set; }

        #endregion
    }
}

CryptoChecker/Controllers/HomeController.cs
namespace CryptoChecker.Controllers
{
    public class HomeController : Controller
    {
        #region Variables

        private readonly ILogger<HomeController> _logger;

        #endregion

        #region Constructors

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        #endregion

        #region Main Methods

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        #endregion
    }
}

CryptoChecker/Controllers/QuotesController.cs
namespace CryptoChecker.Controllers
{
    public class QuotesController : Controller
    {
        #region Main Methods

        // GET: QuotesController/Details/input
        [HttpPost]
        public ActionResult Details(string input)
        {
            QuotesService api = new();
            QuotesModel quotesModel = api.GetAllQuotes(input);
            return View("Details",quotesModel);
        }

        #endregion
    }
}

CryptoChecker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    @using (Html.BeginForm("Details", "Quotes", FormMethod.Post, new { id = "searchForm" }))
    {
        <div id="search">
            <div id="searchtxt">
                <input type="search" name="input" id="txtSearch" />
            </div>
            <br />
            <div id="searchbtn">
                <input id="Search" type="submit" value="Get Quotes" />
            </div>
        </div>
    }
</div>

<script>
    $(function () {
        $('#searchForm').submit(function () {
            $.ajax({
                url: this.action,
                type: this.method,
                input: txtSearch,
                success: function (result) {
                    $('#resultContainer').html(result);
                }
            });
            return false;
        });
    });
</script>

CryptoChecker/Views/Quotes/Details.cshtml
@model CryptoChecker.Models.QuotesModel

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayTextFor(model => model.Name) - @Html.DisplayTextFor(model => model.Symbol)</h1>

@Html.Partial("List", Model.Currency)

<div>
    <a asp-action="Index" asp-controller="Home">Back</a>
</div>

CryptoChecker/Views/Quotes/List.cshtml
@model IEnumerable<CryptoChecker.Models.Currency>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
        </tr>
}
    </tbody>
</table>

CryptoChecker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CryptoChecker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CryptoChecker.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CryptoChecker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CryptoChecker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>